function isMobileClub(){return window.matchMedia('(max-width: 760px)').matches;}
function getGreetingLabel(){const h=new Date().getHours();if(h<12)return'Bom dia';if(h<18)return'Boa tarde';return'Boa noite';}
function updateMobileGreeting(){const g=document.getElementById('mobileGreetingText');const n=document.getElementById('mobileGreetingName');if(g)g.innerText=`${getGreetingLabel()},`;if(n)n.innerText=currentUser?.name||'Jogador Bebcom';}
function setMobileView(view='home'){if(!isMobileClub())return;document.body.classList.remove('mobile-view-home','mobile-view-universe','mobile-view-inventory','mobile-view-profile');document.body.classList.add(`mobile-view-${view}`);document.querySelectorAll('#mobileBottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.appTab===view));closeMobileScanner(false);window.scrollTo({top:0,behavior:'smooth'});}
function openMobileScanner(){const scanCard=document.getElementById('scanCard');if(!scanCard)return;if(!isMobileClub()){scanCard.scrollIntoView({behavior:'smooth',block:'center'});return;}scanCard.classList.add('mobile-scanner-open');setTimeout(()=>document.getElementById('qrInput')?.focus(),220);}
function closeMobileScanner(clear=false){const scanCard=document.getElementById('scanCard');if(!scanCard)return;scanCard.classList.remove('mobile-scanner-open');if(clear){const input=document.getElementById('qrInput');if(input)input.value='';}}
function setupMobileShell(){const nav=document.getElementById('mobileBottomNav');const fab=document.getElementById('mobileScanFab');if(!nav||!fab)return;if(currentUser?.phone){nav.classList.remove('hidden');fab.classList.remove('hidden');updateMobileGreeting();if(isMobileClub()&&!document.body.className.match(/mobile-view-/)){setMobileView('home');}}}
document.addEventListener('click',e=>{if(!isMobileClub())return;const scanCard=document.getElementById('scanCard');const fab=document.getElementById('mobileScanFab');if(!scanCard?.classList.contains('mobile-scanner-open'))return;if(!scanCard.contains(e.target)&&!fab?.contains(e.target))closeMobileScanner(false);});
window.addEventListener('resize',()=>{if(!isMobileClub()){document.body.classList.remove('mobile-view-home','mobile-view-universe','mobile-view-inventory','mobile-view-profile');closeMobileScanner(false);return;}setupMobileShell();});
const originalSaveSessionForMobile=window.saveSession;if(typeof originalSaveSessionForMobile==='function'){window.saveSession=function patchedSaveSession(user){originalSaveSessionForMobile(user);setTimeout(()=>{setupMobileShell();updateMobileGreeting();},80);};}
document.addEventListener('DOMContentLoaded',()=>setupMobileShell());
